apiVersion: apps/v1
kind: Deployment
metadata:
  name: albumviewer
  namespace: album-viewer
  labels:
    app: albumviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albumviewer
  template:
    metadata:
      labels:
        app: albumviewer
    spec:
      containers:
        - name: albumviewer
          image: "nprodregistry.azurecr.io/albumviewer:latest"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
